on:
  push:
    branches:
      - main
      - 'feature/**'
    paths-ignore:
            - '.github/workflows/*'  
            - README.md  
  workflow_dispatch: 
jobs:
  build:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: write a multi-line message
      run: |
        echo " This demo file shows a"
        echo " very basic and easy-understnad workflow"
